# Generated by Django 5.2.6 on 2025-09-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes')),
                ('instructions', models.TextField(max_length=1000)),
                ('ingredients', models.TextField(max_length=1000)),
            ],
        ),
    ]
